<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menus = [
            [
                "id" => 1,
                "title" => [
                'en' => 'Industry',
                'np' => 'उद्योग',
                ],
                "slug" => "industry",
                "position" => 4,
                "side_position" => 1,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 2,
                "title" => [
                'en' => 'Politics',
                'np' => 'राजनीति',
                ],
                "slug" => "politics",
                "position" => 2,
                "side_position" => 2,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 3,
                "title" => [
                'en' => 'headlines',
                'np' => 'मुख्य समाचार',
                ],
                "slug" => "headlines",
                "position" => 3,
                "side_position" => 3,
                "show_on" => ['footer', "homepage", 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => null,
                ],
                [
                "id" => 4,
                "title" => [
                'en' => 'Economics',
                'np' => 'अर्थतन्त्र',
                ],
                "slug" => "economics",
                "position" => 2,
                "side_position" => 4,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 5,
                "title" => [
                'en' => 'Banking',
                'np' => 'बैङ्किङ',
                ],
                "slug" => "banking",
                "position" => 3,
                "side_position" => 5,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 6,
                "title" => [
                'en' => 'Shares',
                'np' => 'सेयर',
                ],
                "slug" => "shares",
                "position" => 6,
                "side_position" => 6,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 7,
                "title" => [
                'en' => 'videos',
                'np' => 'भिडियो',
                ],
                "slug" => "videos",
                "position" => 7,
                "side_position" => 7,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "content",
                "publish_status" => '1',
                "parent_id" => null,
                ],

                [
                "id" => 8,
                "title" => [
                'en' => 'Infrastructure',
                'np' => 'पूर्वाधार',
                ],
                "slug" => "infrastructure",
                "position" => 5,
                "side_position" => 8,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 9,
                "title" => [
                'en' => 'tourism',
                'np' => 'पर्यटन',
                ],
                "slug" => "tourism",
                "position" => 6,
                "side_position" => 9,
                "show_on" => ['footer', "homepage", 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => null,
                ],
                [
                "id" => 10,
                "title" => [
                'en' => 'Technology',
                'np' => 'सूचना प्रविधि',
                ],
                "slug" => "technology",
                "position" => 7,
                "side_position" => 10,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 11,
                "title" => [
                'en' => 'Opinion',
                'np' => 'विचार',
                ],
                "slug" => "opinion",
                "position" => 8,
                "side_position" => 11,
                "show_on" => ['sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 12,
                "title" => [
                'en' => 'Province',
                'np' => 'प्रदेश',
                ],
                "slug" => "province",
                "position" => 12,
                "side_position" => 12,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 13,
                "title" => [
                'en' => 'Corporate Market',
                'np' => 'कर्पोरेट बजार',
                ],
                "slug" => "corporate-market",
                "position" => 13,
                "side_position" => 13,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 14,
                "title" => [
                'en' => 'Province One',
                'np' => 'प्रदेश १',
                ],
                "slug" => "proince-one",
                "position" => 14,
                "side_position" => 14,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 15,
                "title" => [
                'en' => 'Province Two',
                'np' => 'प्रदेश २',
                ],
                "slug" => "proince-two",
                "position" => 15,
                "side_position" => 15,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 16,
                "title" => [
                'en' => 'Bagmati Province',
                'np' => 'बागमती प्रदेश ',
                ],
                "slug" => "bagmati-province",
                "position" => 16,
                "side_position" => 16,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 17,
                "title" => [
                'en' => 'Gandaki Province',
                'np' => 'गण्डकी प्रदेश',
                ],
                "slug" => "gandaki-province",
                "position" => 17,
                "side_position" => 17,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 18,
                "title" => [
                'en' => 'Lumbini Province',
                'np' => 'लुम्बिनी प्रदेश',
                ],
                "slug" => "lumbini-province",
                "position" => 18,
                "side_position" => 18,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 19,
                "title" => [
                'en' => 'Karnali Province',
                'np' => 'कर्णाली प्रदेश',
                ],
                "slug" => "karnali-province",
                "position" => 19,
                "side_position" => 19,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 20,
                "title" => [
                'en' => 'Province Seven',
                'np' => 'सुदुर पश्चिम प्रदेश ',
                ],
                "slug" => "far-western-province",
                "position" => 20,
                "side_position" => 20,
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => 12,
                ],
                [
                "id" => 21,
                "title" => [
                'en' => 'recommendation',
                'np' => 'सिफारिस',
                ],
                "slug" => "recommendation",
                "position" => 21,
                "side_position" => 21,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 22,
                "title" => [
                'en' => 'Art literature',
                'np' => 'कला साहित्य',
                ],
                "slug" => "art-literature",
                "position" => 22,
                "side_position" => 22,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 23,
                "title" => [
                'en' => 'Agriculture',
                'np' => 'कृषि',
                ],
                "slug" => "agriculture",
                "position" => 23,
                "side_position" => 23,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 24,
                "title" => [
                'en' => 'Cooperative',
                'np' => 'सहकारी',
                ],
                "slug" => "cooperative",
                "position" => 24,
                "side_position" => 24,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 25,
                "title" => [
                'en' => 'Interview',
                'np' => 'अन्तर्वार्ता',
                ],
                "slug" => "interview",
                "position" => 25,
                "side_position" => 25,
                "show_on" => ['sidebar', "homepage"],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 26,
                "title" => [
                'en' => 'blog',
                'np' => 'ब्लग',
                ],
                "slug" => "blog",
                "position" => 26,
                "side_position" => 26,
                "show_on" => ['sidebar', "homepage"],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 27,
                "title" => [
                'en' => 'Photo Feature',
                'np' => 'फोटो फिचर',
                ],
                "slug" => "photo-feature",
                "position" => 27,
                "side_position" => 27,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 28,
                "title" => [
                'en' => 'Auto',
                'np' => 'अटो',
                ],
                "slug" => "auto-mobiles",
                "position" => 28,
                "side_position" => 28,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 29,
                "title" => [
                'en' => 'employment',
                'np' => 'रोजगार',
                ],
                "slug" => "employment",
                "position" => 29,
                "side_position" => 29,
                "show_on" => ['footer', "homepage", 'sidebar'],
                "publish_status" => '1',
                "content_type" => "category",
                "parent_id" => null,
                ],
                [
                "id" => 30,
                "title" => [
                'en' => 'Life Style',
                'np' => 'जीवनशैली',
                ],
                "slug" => "life-style",
                "position" => 30,
                "side_position" => 30,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 31,
                "title" => [
                'en' => 'Startup',
                'np' => 'स्टार्टअप',
                ],
                "slug" => "startup",
                "position" => 31,
                "side_position" => 31,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 32,
                "title" => [
                'en' => 'International',
                'np' => 'अन्तर्राष्ट्रिय',
                ],
                "slug" => "international",
                "position" => 32,
                "side_position" => 32,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 33,
                "title" => [
                'en' => 'News',
                'np' => 'समाचार',
                ],
                "position" => 1,
                "side_position" => 33,
                "slug" => "news",
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 34,
                "title" => [
                'en' => 'entertaintment',
                'np' => 'मनोरंजन',
                ],
                "position" => 34,
                "side_position" => 34,
                "slug" => "entertaintment",
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 35,
                "title" => [
                'en' => 'society',
                'np' => 'समाज',
                ],
                "position" => 35,
                "side_position" => 35,
                "slug" => "society",
                "show_on" => ["header", "homepage", 'footer', 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 36,
                "title" => [
                'en' => 'Special',
                'np' => 'विशेष',
                ],
                "slug" => "special",
                "position" => 36,
                "side_position" => 36,
                "show_on" => ["homepage", 'sidebar'],
                "content_type" => "category",
                "publish_status" => '1',
                "parent_id" => null,
                ],
                [
                "id" => 37,
                "title" => [
                'en' => 'Homepage',
                'np' => 'होमपेज',
                ],
                "slug" => "/",
                "position" => 37,
                "side_position" => 37,
                "show_on" => ['sidebar'],
                "publish_status" => '1',
                "content_type" => "homepage",
                "parent_id" => null,
                ],

        ];
        foreach ($menus as $menuItem) {
            $menu = new Menu();
            if ($menu->where('id', $menuItem['id'])->count() > 0) {
                $menu = $menu->where('id', $menuItem['id'])->first();
            }
            $menu->fill($menuItem);
            $menu->save();
        }
    }
}
