<<<<<<< HEAD
<<<<<<< HEAD
theme: jekyll-theme-architect
=======
theme: jekyll-theme-architect
>>>>>>> 9e6a5f1ba4fb1b77879ee0c20aab69b504c0300e
=======
theme: jekyll-theme-architect
>>>>>>> 9e6a5f1ba4fb1b77879ee0c20aab69b504c0300e
